### PR TITLE
Augmenter

### PR DESCRIPTION
**Pull request by FranzHahn**
handled issues #1 , #2 and #3 .

### CODE REVIEW

**Review by subpic — APPROVED** [review]

**Review by subpic — APPROVED** [review]

**Review by subpic — APPROVED** [review]

**Review by subpic — APPROVED** [review]
get_patch_dims is a generic utility function that does not require access to an image per se. It is sufficient for it to know the size of the image (width, height). The first argument can then be the size of the image, rather than the image itself.

**Review by subpic — CHANGES_REQUESTED** [review]
In def cropout_patch(im, patch_size=(224, 224), X1 and Y1 are used without being initialized? Am I reading this correctly?

**Comment by FranzHahn** [comment]
> In def cropout_patch(im, patch_size=(224, 224), X1 and Y1 are used without being initialized? Am I reading this correctly?

Should be fixed. I also added tests and sanity checks.

**Review by subpic — APPROVED** [review]

**Review by subpic — APPROVED** [review]

**Review by subpic — APPROVED** [review]

**Review by subpic — APPROVED** [review]

**Comment by subpic** [comment]
Integrated by separate commits.

**Pull request closed without merging**
